### PR TITLE
Use `ServantError` to report Errors instead of `String`

### PR DESCRIPTION
**Pull request by tvh**
This is related to #12

### CODE REVIEW

**Comment by tvh** [comment]
Just noticed there are a few bits missing, but welcome for feedback.

**Comment by tvh** [comment]
Ready for review

**Comment by jkarni** [comment]
Looks good. Could we have tests that check that the other constructors (`UnsupportedContentType`, `DecodeFailure`...) are returned appropriately?

**Comment by alpmestan** [comment]
Nice, that'll be much cleaner for users to understand. +1 on Julian's comment regarding tests to make sure the various errors are properly reported, and only when appropriate. Aside from that, :+1:

**Comment by tvh** [comment]
This has tests for all reported errors now.

**Comment by alpmestan** [comment]
Wonderful. Thank you!

**Pull request merged**
